In [2]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

weather = pd.read_csv('weatherHistory-mini.csv')
print(weather.isna().sum()) # Find a data is lose in your file

Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           3
Wind Bearing (degrees)      0
Visibility (km)             0
Pressure (millibars)        0
dtype: int64


In [4]:
boolean_missing = weather.isna().any(axis=1)  # Show all row that are missing 
weather_missing = weather[boolean_missing]
print(weather_missing)

          Summary Precip Type  Temperature (C)  Apparent Temperature (C)  \
4   Partly Cloudy        snow         -0.96111                  -0.96111   
8        Overcast        snow         -1.13889                  -5.05000   
13          Clear        snow         -2.74444                  -9.10556   

    Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
4       0.98                NaN                       0           4.0733   
8       0.87                NaN                     310           9.9820   
13      0.45                NaN                      17          10.5777   

    Pressure (millibars)  
4                1033.82  
8                1022.26  
13               1025.94  


In [6]:
missing_vars = ['Wind Speed (km/h)'] #Set value of Wind Speed (km/h) from missing values back to simple data with none missing values
indpend_vars = ['Temperature (C)','Wind Bearing (degrees)']
imputer = IterativeImputer()
imputed_data = imputer.fit_transform(weather[indpend_vars+missing_vars])
print(imputed_data)

[[  7.777778   288.          14.4095    ]
 [  0.983333   186.           8.2593    ]
 [  2.755556    18.          17.2914    ]
 [  0.627778   340.           6.6654    ]
 [ -0.96111      0.          19.88811769]
 [ -2.06111    145.           3.6386    ]
 [  8.861111   258.          10.8836    ]
 [ 11.45556    132.          15.3594    ]
 [ -1.13889    310.           8.64200791]
 [  2.861111   190.          10.5777    ]
 [  2.866667   170.          10.2396    ]
 [  2.222222    32.          22.0892    ]
 [ -2.22778     39.          24.955     ]
 [ -2.74444     17.          19.26335655]
 [  5.972222   140.          24.2305    ]]


In [7]:
#Take Wind Speed where is non missing values from inputed_data 
# take to new DataFrame name weather and display it
weather[missing_vars] = imputed_data[:,-len(missing_vars):] #or weather[missing_vars] = imputed_data[:-,1:]
display(weather)


Summary Precip Type  Temperature (C)  Apparent Temperature (C)  \
0   Partly Cloudy        rain         7.777778                  5.272222   
1           Foggy        rain         0.983333                 -1.644440   
2        Overcast        rain         2.755556                 -1.366670   
3        Overcast        rain         0.627778                 -1.533330   
4   Partly Cloudy        snow        -0.961110                 -0.961110   
5           Foggy        snow        -2.061110                 -2.061110   
6   Mostly Cloudy        rain         8.861111                  7.133333   
7   Partly Cloudy        rain        11.455560                 11.455560   
8        Overcast        snow        -1.138890                 -5.050000   
9           Foggy        rain         2.861111                 -0.016670   
10  Mostly Cloudy        rain         2.866667                  0.072222   
11       Overcast        rain         2.222222                 -2.688890   
12          Clear        snow        -2.227780                 -8.744440   
13          Clear        snow        -2.744440                 -9.105560   
14       Overcast        rain         5.972222                  1.861111   

    Humidity  Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  \
0       0.88          14.409500                     288           8.1305   
1       0.93           8.259300                     186           1.3202   
2       0.90          17.291400                      18           7.9051   
3       0.92           6.665400                     340           7.0357   
4       0.98          19.888118                       0           4.0733   
5       1.00           3.638600                     145           0.0322   
6       0.93          10.883600                     258           3.9767   
7       0.69          15.359400                     132           9.9820   
8       0.87           8.642008                     310           9.9820   
9       0.96          10.577700                     190           2.9302   
10      0.88          10.239600                     170          14.0875   
11      0.84          22.089200                      32          11.2056   
12      0.61          24.955000                      39          11.2056   
13      0.45          19.263357                      17          10.5777   
14      0.80          24.230500                     140          11.2700   

    Pressure (millibars)  
0                1025.05  
1                1036.54  
2                1023.65  
3                1041.05  
4                1033.82  
5                1026.67  
6                1018.35  
7                1013.78  
8                1022.26  
9                1000.50  
10               1011.79  
11               1015.80  
12               1011.39  
13               1025.94  
14               1009.39

In [9]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
data = pd.read_csv('data6.csv')
print(data.isna().sum()) #Find which data is missing in your data file
missing_vars = ['BloodPressure']
indpend_vars = ['BMI','Age']
imputer = IterativeImputer()
imputed_data = imputer.fit_transform(data[indpend_vars+missing_vars])
data[missing_vars] = imputed_data[:,-1:]
ind = [81,435,604]
display(data.iloc[ind])


Pregnancies                  0
Glucose                      0
BloodPressure               35
SkinThickness                0
Insulin                      0
BMI                          0
DiabetesPedigreeFunction     0
Age                          0
Outcome                      0
dtype: int64


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
81             2       74      54.726486              0        0   0.0   
435            0      141      75.240562              0        0  42.4   
604            4      183      71.639796              0        0  28.4   

     DiabetesPedigreeFunction  Age  Outcome  
81                      0.102   22        0  
435                     0.205   29        1  
604                     0.212   36        1